spring:
  profiles:
   include: pro
  datasource:
    username: dzyz
    password: dz45$yz
    url: jdbc:mysql://172.16.30.86:3306/sealquery?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

myproject:
  name: pro