spring:
  profiles:
    include: dev
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.45:3306/sealquery?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.gaskey.impressionService.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8013

myproject:
  name: test