spring:
  profiles:
    include: dev
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/sealquery?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    #url: jdbc:mysql://192.168.1.45:3306/sealquery?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
server:
  port: 8013

myproject:
  name: test